## Nettoyage des données des Valeurs Foncières 2019-S2

In [12]:
#### EXPLORING THE DATASET ####
import pandas as pd

# Read in the data
df_2019 = pd.read_csv('ValeursFoncieres-2019-S2.txt', delimiter='|')

df_2019.head()

/var/folders/ql/7rnwb81s5ms8q8f6v8hbbkb00000gn/T/ipykernel_2656/197503464.py:5: DtypeWarning: Columns (14,18,23,24,26,28,31,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2019 = pd.read_csv('ValeursFoncieres-2019-S2.txt', delimiter='|')

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,01/07/2019,Vente,...,NaN,0,1.0,Maison,NaN,150.0,5.0,S,NaN,695.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/07/2019,Vente,...,NaN,0,1.0,Maison,NaN,94.0,4.0,AG,NaN,888.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/07/2019,Vente,...,NaN,0,1.0,Maison,NaN,94.0,4.0,S,NaN,500.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,04/07/2019,Vente,...,NaN,0,1.0,Maison,NaN,90.0,3.0,S,NaN,522.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/07/2019,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,8.0

In [13]:
#### BASIC INFO ABOUT THE DATA ####
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1967866 entries, 0 to 1967865
Data columns (total 43 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Identifiant de document     float64
 1   Reference document          float64
 2   1 Articles CGI              float64
 3   2 Articles CGI              float64
 4   3 Articles CGI              float64
 5   4 Articles CGI              float64
 6   5 Articles CGI              float64
 7   No disposition              int64
 8   Date mutation               object
 9   Nature mutation             object
 10  Valeur fonciere             object
 11  No voie                     float64
 12  B/T/Q                       object
 13  Type de voie                object
 14  Code voie                   object
 15  Voie                        object
 16  Code postal                 float64
 17  Commune                     object
 18  Code departement            object
 19  Code commune                int64
 20  Prefixe de section          float64
 21  Section                     object
 22  No plan                     int64
 23  No Volume                   object
 24  1er lot                     object
 25  Surface Carrez du 1er lot   object
 26  2eme lot                    object
 27  Surface Carrez du 2eme lot  object
 28  3eme lot                    object
 29  Surface Carrez du 3eme lot  object
 30  4eme lot                    float64
 31  Surface Carrez du 4eme lot  object
 32  5eme lot                    float64
 33  Surface Carrez du 5eme lot  object
 34  Nombre de lots              int64
 35  Code type local             float64
 36  Type local                  object
 37  Identifiant local           float64
 38  Surface reelle bati         float64
 39  Nombre pieces principales   float64
 40  Nature culture              object
 41  Nature culture speciale     object
 42  Surface terrain             float64
dtypes: float64(17), int64(4), object(22)
memory usage: 645.6+ MB

In [14]:
#### SHOW IF THERE ARE MISSING VALUES ####
df_2019.isnull().sum()

Identifiant de document       1967866
Reference document            1967866
1 Articles CGI                1967866
2 Articles CGI                1967866
3 Articles CGI                1967866
4 Articles CGI                1967866
5 Articles CGI                1967866
No disposition                      0
Date mutation                       0
Nature mutation                     0
Valeur fonciere                 22413
No voie                        796474
B/T/Q                         1883115
Type de voie                   818871
Code voie                       18716
Voie                            18726
Code postal                     18821
Commune                             0
Code departement                    0
Code commune                        0
Prefixe de section            1872452
Section                            73
No plan                             0
No Volume                     1962182
1er lot                       1349206
Surface Carrez du 1er lot     1805137
2eme lot                      1842563
Surface Carrez du 2eme lot    1927701
3eme lot                      1946927
Surface Carrez du 3eme lot    1963779
4eme lot                      1960659
Surface Carrez du 4eme lot    1966700
5eme lot                      1964379
Surface Carrez du 5eme lot    1967260
Nombre de lots                      0
Code type local                871274
Type local                     871274
Identifiant local             1967866
Surface reelle bati            872802
Nombre pieces principales      872802
Nature culture                 627235
Nature culture speciale       1881162
Surface terrain                627235
dtype: int64

In [15]:
#### DELETE THE COLUMNS WHERE THERE ARE MORE THAN 50% MISSING VALUES ####

threshold = len(df_2019)*0.5
df_2019 = df_2019.dropna(axis=1, thresh = threshold)
df_2019.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,Type de voie,Code voie,Voie,Code postal,Commune,...,Code commune,Section,No plan,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Nature culture,Surface terrain
0,1,01/07/2019,Vente,"244200,00",73.0,RUE,0958,COMMANDANT COUSTEAU,1000.0,BOURG-EN-BRESSE,...,53,CN,405,0,1.0,Maison,150.0,5.0,S,695.0
1,1,04/07/2019,Vente,"195000,00",852.0,CHE,0170,DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,...,184,AM,237,0,1.0,Maison,94.0,4.0,AG,888.0
2,1,04/07/2019,Vente,"195000,00",852.0,CHE,0170,DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,...,184,AM,237,0,1.0,Maison,94.0,4.0,S,500.0
3,1,04/07/2019,Vente,"110030,00",5041.0,NaN,B097,LA VILLE,1250.0,GRAND-CORENT,...,177,B,764,0,1.0,Maison,90.0,3.0,S,522.0
4,1,03/07/2019,Vente,"160450,00",NaN,NaN,B039,CHARBONNET,1270.0,COLIGNY,...,108,AH,10,0,NaN,NaN,NaN,NaN,S,8.0

In [16]:
#### CHECK IF VALEUR FONCIERE IS NULL ####
df_2019.isnull().sum()

No disposition                    0
Date mutation                     0
Nature mutation                   0
Valeur fonciere               22413
No voie                      796474
Type de voie                 818871
Code voie                     18716
Voie                          18726
Code postal                   18821
Commune                           0
Code departement                  0
Code commune                      0
Section                          73
No plan                           0
Nombre de lots                    0
Code type local              871274
Type local                   871274
Surface reelle bati          872802
Nombre pieces principales    872802
Nature culture               627235
Surface terrain              627235
dtype: int64

In [17]:
#### DELETE ROWS WHERE 'VALEUR FONCIERE' IS NULL ####
df_2019.dropna(subset=['Valeur fonciere'], inplace=True)
df_2019.head()

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,Type de voie,Code voie,Voie,Code postal,Commune,...,Code commune,Section,No plan,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Nature culture,Surface terrain
0,1,01/07/2019,Vente,"244200,00",73.0,RUE,0958,COMMANDANT COUSTEAU,1000.0,BOURG-EN-BRESSE,...,53,CN,405,0,1.0,Maison,150.0,5.0,S,695.0
1,1,04/07/2019,Vente,"195000,00",852.0,CHE,0170,DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,...,184,AM,237,0,1.0,Maison,94.0,4.0,AG,888.0
2,1,04/07/2019,Vente,"195000,00",852.0,CHE,0170,DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,...,184,AM,237,0,1.0,Maison,94.0,4.0,S,500.0
3,1,04/07/2019,Vente,"110030,00",5041.0,NaN,B097,LA VILLE,1250.0,GRAND-CORENT,...,177,B,764,0,1.0,Maison,90.0,3.0,S,522.0
4,1,03/07/2019,Vente,"160450,00",NaN,NaN,B039,CHARBONNET,1270.0,COLIGNY,...,108,AH,10,0,NaN,NaN,NaN,NaN,S,8.0

In [18]:
#### DELETE COLUMNS WE DONT WANT TO ANALYSE ####
df_2019.drop(['No voie', 'Type de voie', 'Nature culture',  'Section',  'No plan', 'No disposition', 'Code voie'], axis=1, inplace=True)
df_2019.head()

,Date mutation,Nature mutation,Valeur fonciere,Voie,Code postal,Commune,Code departement,Code commune,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain
0,01/07/2019,Vente,"244200,00",COMMANDANT COUSTEAU,1000.0,BOURG-EN-BRESSE,1,53,0,1.0,Maison,150.0,5.0,695.0
1,04/07/2019,Vente,"195000,00",DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,1,184,0,1.0,Maison,94.0,4.0,888.0
2,04/07/2019,Vente,"195000,00",DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,1,184,0,1.0,Maison,94.0,4.0,500.0
3,04/07/2019,Vente,"110030,00",LA VILLE,1250.0,GRAND-CORENT,1,177,0,1.0,Maison,90.0,3.0,522.0
4,03/07/2019,Vente,"160450,00",CHARBONNET,1270.0,COLIGNY,1,108,0,NaN,NaN,NaN,NaN,8.0

In [19]:
#### REPLACE MISSING VALUES IN COLUMNS WE WANT ####
df_2019.fillna(0, inplace=True)
df_2019.head()

,Date mutation,Nature mutation,Valeur fonciere,Voie,Code postal,Commune,Code departement,Code commune,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain
0,01/07/2019,Vente,"244200,00",COMMANDANT COUSTEAU,1000.0,BOURG-EN-BRESSE,1,53,0,1.0,Maison,150.0,5.0,695.0
1,04/07/2019,Vente,"195000,00",DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,1,184,0,1.0,Maison,94.0,4.0,888.0
2,04/07/2019,Vente,"195000,00",DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,1,184,0,1.0,Maison,94.0,4.0,500.0
3,04/07/2019,Vente,"110030,00",LA VILLE,1250.0,GRAND-CORENT,1,177,0,1.0,Maison,90.0,3.0,522.0
4,03/07/2019,Vente,"160450,00",CHARBONNET,1270.0,COLIGNY,1,108,0,0.0,0,0.0,0.0,8.0

In [20]:
#### CHECK TYPE ####
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1945453 entries, 0 to 1967865
Data columns (total 14 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Date mutation              object
 1   Nature mutation            object
 2   Valeur fonciere            object
 3   Voie                       object
 4   Code postal                float64
 5   Commune                    object
 6   Code departement           object
 7   Code commune               int64
 8   Nombre de lots             int64
 9   Code type local            float64
 10  Type local                 object
 11  Surface reelle bati        float64
 12  Nombre pieces principales  float64
 13  Surface terrain            float64
dtypes: float64(5), int64(2), object(7)
memory usage: 222.6+ MB

In [21]:
#### CONVERTS TO THE RIGHT TYPE ####

category_convert = ['Nature mutation', 'Voie', 'Code postal', 'Commune', 'Code departement', 'Code commune', 'Code type local', 'Type local']
df_2019[category_convert] = df_2019[category_convert].astype('category')

df_2019['Date mutation'] = pd.to_datetime(df_2019['Date mutation'], errors = 'coerce')

df_2019['Valeur fonciere']=df_2019['Valeur fonciere'].replace({'\xa0':'',',':'.'}, regex=True)
df_2019['Valeur fonciere']=pd.to_numeric(df_2019['Valeur fonciere'], errors='coerce')

df_2019.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1945453 entries, 0 to 1967865
Data columns (total 14 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Date mutation              datetime64[ns]
 1   Nature mutation            category
 2   Valeur fonciere            float64
 3   Voie                       category
 4   Code postal                category
 5   Commune                    category
 6   Code departement           category
 7   Code commune               category
 8   Nombre de lots             int64
 9   Code type local            category
 10  Type local                 category
 11  Surface reelle bati        float64
 12  Nombre pieces principales  float64
 13  Surface terrain            float64
dtypes: category(8), datetime64[ns](1), float64(4), int64(1)
memory usage: 141.7 MB

In [22]:
#### CHECK FOR DUPLICATES ####
df_2019.duplicated().sum()

213219

In [23]:
#### DELETE DUPLICATES ####

df_2019.drop_duplicates(keep='last', inplace=True)
df_2019.duplicated().sum()

0

In [24]:
df_2019.head()

,Date mutation,Nature mutation,Valeur fonciere,Voie,Code postal,Commune,Code departement,Code commune,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Surface terrain
0,2019-01-07,Vente,244200.0,COMMANDANT COUSTEAU,1000.0,BOURG-EN-BRESSE,1,53,0,1.0,Maison,150.0,5.0,695.0
1,2019-04-07,Vente,195000.0,DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,1,184,0,1.0,Maison,94.0,4.0,888.0
2,2019-04-07,Vente,195000.0,DE LA CROIX ROSIER,1250.0,HAUTECOURT-ROMANECHE,1,184,0,1.0,Maison,94.0,4.0,500.0
3,2019-04-07,Vente,110030.0,LA VILLE,1250.0,GRAND-CORENT,1,177,0,1.0,Maison,90.0,3.0,522.0
4,2019-03-07,Vente,160450.0,CHARBONNET,1270.0,COLIGNY,1,108,0,0.0,0,0.0,0.0,8.0

In [25]:
#### SAVE DATAFRAME ####

#df_2019.to_csv('df_2019.csv', index=False)